### ISSUE TITLE
blue background and white vertical lines after executing nvim on centos7

### ISSUE THREAD

**Issue by rpolasek-sde** [nvim-lua/kickstart.nvim#66] opened 2022-12-19 12:17 UTC
when i execute `nvim --clean` blue background and white vertical lines disappear. a problem may be old _centos7_ but could anybody confirm that, please? `nvim` has been compiled based on latest sources from _github_ using `gcc-12.1.0` and `python-3.6` is used.

you can see a screen-shot here 
https://www.dropbox.com/s/63b0l8bpeainhkh/Screenshot%20from%202022-12-19%2013-09-50.png?dl=0

**Comment by tjdevries** [comment] 2022-12-19 22:53
What terminal are you using? It must not support true colors would be my guess.

**Comment by RitikDutta** [comment] 2022-12-20 02:40
Try with the nvim --debug flag to see if this produces any info that might help to identify the cause of the issue.

**Comment by tjdevries** [comment] 2022-12-20 02:42
What `--debug` flag?

**Comment by rpolasek-sde** [comment] 2022-12-20 04:57
```
$ nvim --debug
nvim: Unknown option argument: "--debug"
More info with "nvim -h"
```

i'm using defaut _centos7_ terminal ad it should support true colors because my `vim` doesn't have any problem...

```
$ echo $TERM
xterm-256color
```

and if i use it in the `screen` it uses settings below:
```
# 256 colors
attrcolor b ".I"
termcapinfo xterm* 'is=\E[r\E[m\E[2J\E[H\E[?7h\E[?1;4;6l'
termcapinfo xterm 'Co#256:AB=\E[48;5;%dm:AF=\E[38;5;%dm'
term screen-256color
defbce "on"
```

**Comment by tjdevries** [comment] 2022-12-20 17:53
well if you're using screen, then it's not actually xterm, so you probably want to change your $TERM value. There are quite a few issues and mentions of this in neovim/neovim: https://github.com/neovim/neovim/wiki/FAQ#nvim-shows-weird-symbols-2-q-when-changing-modes

I'll close this cause I don't think we'll be able to fix this -- feel free to use a different color scheme and remove `termguicolors` from the options.

**Closed by tjdevries** 2022-12-20 17:53 UTC
