### ISSUE TITLE
Can you please add example of launch json for debug

### ISSUE THREAD

**Issue by SamPosh** [nvim-lua/kickstart.nvim#279] opened 2023-04-23 12:51 UTC
I’m new to nvim. Currently I’m using vscode and would like to check nvim. I mainly use launch.json for debug configuration. I tried vscode launch json in nvim but it fails. Can you please add a sample for it?

it will be helpful for many people from vscode.

**Comment by feoh** [comment] 2023-04-24 01:47
Hi there and thanks for the report!

The problem is that we'd need someone who's already familiar with configuring the sort of advanced VSCode debugging you want to write this tutorial.

If anybody reading this feels like volunteering, that's great, please do!

May I suggest rather than looking for a way to convert one to the other to simply follow through the instructions already included in kickstart.nvim to add debugging support?

You can find them [here](https://github.com/nvim-lua/kickstart.nvim/blob/master/lua/kickstart/plugins/debug.lua).

The idea is to help *you* build exactly the debugging environment you want! :)

You can do it with just a few minutes or maybe a couple of hours spent reading documentation and trying things out.  If you have specific questions, feel free to ask them here!

I'm closing this for now. Good luck with your journey!

**Closed by feoh** 2023-04-24 01:47 UTC
