### ISSUE TITLE
my VIM background color changed to be blue

### ISSUE THREAD

**Issue by arwysyah** [nvim-lua/kickstart.nvim#490] opened 2023-11-06 04:56 UTC
## Describe the bug

My Vim background color are blue 

if I removed the installation from init.lua, it is gonna back to default/standard color

how I can fix that ?

## To Reproduce

install from taking the source code (init.lua)
1. I installed by copied init.lua and paste to my init.lua config =>changed my background to become blue

1. I removed config folder and re install it
2. I installed as well from cloning the git ,=> it also changed my background to become blue
## Desktop

- OS: Ventura 13.6
- Terminal: Terminal 2.13

## Neovim Version

```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1699180677

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.4/share/nvim"
```

<img width="341" alt="Screenshot 2023-11-06 at 11 46 30" src="https://github.com/nvim-lua/kickstart.nvim/assets/55026697/38aa7bc1-2f53-4422-9ca6-a9c4068931cc">

**Comment by iamyeizi** [comment] 2023-11-06 20:34
same to me, idk why jaja

**Comment by feoh** [comment] 2023-11-07 15:00
Folks, this is the 'onedark' theme included with kickstart.nvim

If you wish to change it, create a local fork and do that like I did in [mine](https://github.com/feoh/kickstart.nvim).

Closing this as it's working as designed.

**Closed by feoh** 2023-11-07 15:00 UTC

**Comment by feoh** [comment] 2023-11-07 15:15
The default Apple terminal IMO showcases one of the frustrating aspects of Mac (Which I LOVE generally BTW).

There are certain parts of the ecosystem that Apple just straight up ignores rather than adopting obviously superior alternatives from open source.

Pretty sure the Apple Terminal hasn't meaningfully changed since the days of NextSTEP :(

Please choose an alternative like iTerm2, Alacritty or Kitty.
