### ISSUE TITLE
Error message appearing at every initialization - "No specs found for module custom.plugins"

### ISSUE THREAD

**Issue by Stopfield** [nvim-lua/kickstart.nvim#204] opened 2023-02-27 18:31 UTC
**Describe the bug**
After executing `nvim`, the following error appears every time:

```
Error detected while processing .../.config/nvim/init.lua
No specs found for module custom.plugins
All parsers are up to date
```

This doesn't impede `nvim` to work, but it's really annoying.

**To Reproduce**
1. Install nvim
2. Copy the `init.lua` file into `.../config/nvim/`
3. Run the first installation
4. The prior message will appear

**Desktop (please complete the following information):**
- OS: `Linux Mint 21.1 x86_64`
- Terminal: `gnome-terminal (using bash 5.1.16)`

** Neovim Version **
 - NVIM v0.8.3

More info about the version:
- Build type: Release
- LuaJIT 2.1.0-beta3

```
```

**Comment by TheSleepingAssassin** [comment] 2023-02-27 18:54
I encountered the same error, after browsing the config for a bit it was an easy fix comment the code on line 189 which says
`{ import = 'custom.plugins' },`
This error is produced when there are not already any packages located in lua/custom/plugins. Commenting that line should be an easy fix.

**Comment by Stopfield** [comment] 2023-02-27 19:24
Thanks! Should we leave the issue open? Maybe, we could use some automated function to detect custom plugins beforehand

**Comment by joaco05** [comment] 2023-02-27 19:29
I think that we should i also ran into the same problem

**Comment by arjun7965** [comment] 2023-03-19 04:15
Is there a fix for this?

**Comment by AIGeneratedUsername** [comment] 2023-03-25 14:57
> I faced the same issue. Is there a fix for this?

The fix is to clone a whole repository, and not only `init.lua`.  Or do what is described above https://github.com/nvim-lua/kickstart.nvim/issues/204#issuecomment-1446880068

**Comment by SiddharthReddy30** [comment] 2023-04-10 17:48
i got the same error

**Comment by SiddharthReddy30** [comment] 2023-04-13 08:48
> 

Just comment out line 189, you will be good.
I just submitted a fix with PR#263 hopefully they merge it.

**Comment by feoh** [comment] 2023-04-13 15:10
Hiya! The problem here is showcased in your steps to reproduce.

You must copy the entirety of the kickstart.nvim into your ~/.config/nvim in order for it to work, not just init.lua.

Closing.

**Closed by feoh** 2023-04-13 15:10 UTC

**Comment by nPHYN1T3** [comment] 2023-04-24 18:39
"You must copy the entirety of the kickstart.nvim into your ~/.config/nvim in order for it to work, not just init.lua."

Statements like this make me feel like I'm losing my mind. I read the install README, I watched the video and there is no mention of "copy the entirety of the kickstart.nvim" unless I've read so much everything has blurred into vague nothingness that just hits my eyes and vanishes before it's processed.

**Comment by nPHYN1T3** [comment] 2023-04-24 20:14
One big hurdle for this would be that there is a very popular video that kinda instigates this issue. That would need to be revised heh.

Well for starters if I was to re-write the read me I'd need some input. Like why does the install section gloss over what the video says. i.e. The video says hey just copy the contents of the init.lua and BLAM!? The read me also doesn't really tell you how to do anything. Just kinda says clone the git repo and GLHF.

Then as for the "You must copy the entirety of the kickstart.nvim into your ~/.config/nvim in order for it to work" this is also ambiguous. It doesn't say zip/folder/files. First where do you get those files? First you need to get the zip by clicking on the blue CODE button because there are no release files. Then what? Well then extract the FILES in that archive to your neovim folder ~/.config/nvim. Given the archive has the init.lua what the he11 is the video talking about?! heh.

Cheeky stuff aside it would be a lot clearer if the READ ME had some defined sections. Install via GIT, install via Archive. Hey special note ignore the video we've linked to as it will confuse/complicate things since you NEED to either clone the GIT or download the WHOLE archive.

**Comment by feoh** [comment] 2023-04-24 20:20
I have a better idea. Since you feel so strongly about this, why don't YOU make a Youtube video reflecting the current reality instead?

Open source is a gift. That video @tjdevries was another gift. The fact that he gave us that gift some time ago which means it's no longer 100% accurate doesn't mean that we get to be grabby and *demand* another one.

I'll review the README and see if there's anything further I can add to help this situation. Sorry you had trouble.

**Comment by feoh** [comment] 2023-04-24 20:23
Can't say I blame you. I have one but I don't love it :) Thanks a bunch I look forward to your pull request!

**Comment by nPHYN1T3** [comment] 2023-04-24 20:32
Lol pull request. The primary reason I have an account here was bug reporting. I tried to learn all this git stuff but it does not jive for me. Apparently I'm a living Roger Murtaugh quote.

**Comment by feoh** [comment] 2023-04-24 20:39
I'm afraid pull requests are the coin of the realm for open source projects. There are a million billion resources out there to help you understand how to use Github.

**Comment by nPHYN1T3** [comment] 2023-04-24 20:46
Sadly I know, I could write it out in here and you could incorporate whatever you wanted but instead I've got to branch and or fork and yada yada. I've read the docs and sadly they also read very much like if you know you'll get it if you don't it will just be a wall of text. You've got to jump around cross referencing things to build the whole picture and cue my Roger Murtaugh joke.

I will perhaps give it another go shortly.

**Comment by duyminhle95** [comment] 2023-06-13 03:16
> import = 'custom.plugins'

thanks so much <3

**Comment by diponkumer** [comment] 2023-06-15 06:31
> I encountered the same error, after browsing the config for a bit it was an easy fix comment the code on line 189 which says `{ import = 'custom.plugins' },` This error is produced when there are not already any packages located in lua/custom/plugins. Commenting that line should be an easy fix.

Thanks it works , though it was in 205 number line for me.

**Comment by abdelrahman-essawy** [comment] 2023-08-01 14:22
What fixed it for me that, I had to make file 

```\custom\plugins.lua``` 

and typed inside it :
```lua
return {}
```

**Comment by samcdavid** [comment] 2024-03-21 15:16
To fix `no specs found for module lazyvim.plugins.extras.editor.symbols-outline` I commented out:
```
{ import = "lazyvim.plugins.extras.editor.symbols-outline" },
```
in my lua/config/lazy.lua file. After restarting nvim, I didn't get the issue anymore.

**Comment by ashokgelal** [comment] 2024-10-11 15:58
My solution for this was to create`plugins.lua` file with contents:

```lua
return {}
```

```bash
mkdir -p ~/.config/nvim/lua
echo "return {}" > ~/.config/nvim/lua/plugins.lua
```

**Comment by ShadowProgging** [comment] 2024-10-27 22:05
> Hiya! The problem here is showcased in your steps to reproduce.
> 
> You must copy the entirety of the kickstart.nvim into your ~/.config/nvim in order for it to work, not just init.lua.
> 
> Closing.

The [installation howto](https://lazy.folke.io/installation) doesn't say anything about a kickstart.nvim

**Comment by LuisBL** [comment] 2026-01-01 20:06
Fresh install today with and without ` ~/.config/nvim/lua/plugins.lua ` I get the same error

```
$ lazygit --version
commit=17d03ec8cb89d4c65fd129228164562a220abefb, build date=2025-12-06T13:01:50Z, build source=binaryRelease, version=0.57.0, os=linux, arch=amd64, git version=2.34.1
$

$ tree ~/.config/nvim
/home/luis/.config/nvim
├── LICENSE
├── README.md
├── init.lua
├── lazy-lock.json
├── lazyvim.json
├── lua
│   ├── config
│   │   ├── autocmds.lua
│   │   ├── fzf.lua
│   │   ├── keymaps.lua
│   │   ├── lazy.lua
│   │   └── options.lua
│   ├── plugins
│   │   ├── example.lua
│   │   └── noice.lua
│   └── plugins.lua
└── stylua.toml

3 directories, 14 files
$ cat ~/.config/nvim/lua/plugins.lua 
return {}
$ 
```

<img width="1920" height="1200" alt="Image" src="https://github.com/user-attachments/assets/075ea9e9-09bf-4881-93a2-5409521b0902" />
