### ISSUE TITLE
Pressing `<Leader>g` causes the cursor to advance 1 character

### ISSUE THREAD

**Issue by robinjam** [nvim-lua/kickstart.nvim#821] opened 2024-04-02 23:08 UTC
## Describe the bug

Bit of a weird one. When I press `<Leader>g`, the cursor advances forward one character. The WhichKey pane still appears, and I can still follow up with `r`, `d`, etc., and those bindings all function as expected.

I've not noticed this issue with any other key combination (though I haven't exhaustively checked).

`:checkhealth` output looks fairly normal, but the WhichKey section shows this (not sure if it's an issue/related):

```
which-key: require("which-key.health").check()

WhichKey: checking conflicting keymaps ~
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"sF"**
- rhs: ` `
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"sr"**
- rhs: ` `
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"sh"**
- rhs: ` `
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"sd"**
- rhs: ` `
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"sf"**
- rhs: ` `
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"gc"**
- rhs: `<Plug>(comment_toggle_linewise)`
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"gb"**
- rhs: `<Plug>(comment_toggle_blockwise)`
```

I tried checking out the latest Kickstart `master`, deleting `~/.local/share/nvim` and relaunching nvim, and the issue persists.

## To Reproduce

1. Press `<Leader>g`. Notice that the cursor advanced one character, but vim is still awaiting input (and WhichKey is open).

## Desktop

- OS: macOS 13.6.6
- Terminal: iTerm2

## Neovim Version

```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1710088188

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.5/share/nvim"

Run :checkhealth for more info
```

**Comment by iton0** [comment] 2024-04-03 16:41
Are you use the default config for WhichKey from main or have you made any changes?

**Comment by feoh** [comment] 2024-04-04 16:12
Thanks for the report and good catch! I can reproduce this on kickstart latest but have no idea what's going on.

I'll see if I can find the time to dig into this.

**Comment by dam9000** [comment] 2024-04-04 16:38
I think that's the intended behaviour. If a starting key combo does not match any defined combo, then the broken down keys are interpreted instead. A single space in normal mode if not remapped just advances the cursor for 1 character right so that what happens. As for then getting a which-key popup it's because the `g` key then waits for the next movement key combo. If you try space and x what will happen is cursor advances one char and deletes one char, without any which-key popup.
What was your expectation with space-g anyway?

**Comment by iton0** [comment] 2024-04-04 16:52
I think I see the issue: the init.lua does not have the <leader>g key chain. 
@robinjam try adding this to the require('which-key').register({}) section of your whichkey config and see if the issue persists:
`['<leader>g'] = { name = '[G]it', _ = 'which_key_ignore' },`

**Comment by feoh** [comment] 2024-04-04 20:34
You're right. This is working as designed. Closing.

**Closed by feoh** 2024-04-04 20:34 UTC

**Comment by robinjam** [comment] 2024-04-04 21:33
You're absolutely right, I got my keybinds mixed up 🤦‍♂️

Sorry for the time waste
