### ISSUE TITLE
Formatting with LSP closes folds

### ISSUE THREAD

**Issue by ChrisWellsWood** [nvim-lua/kickstart.nvim#401] opened 2023-08-18 13:46 UTC
## Describe the bug
When I format with the LSP, the fold I'm currently in closes. This happens when using `:Format` or on save with the `autoformat` plugin. I don't want this to happen and I can't see a vim option that seems to relate to this or an options specific to the LSP. Thanks for making `kickstart.nvim, it's fantastic!

## To Reproduce

1. Set:
```lua
vim.o.foldmethod = 'marker'
vim.o.foldmarker = '{{{,}}}'
```
2. Run `:Format` while inside a manually defined fold like this:
```rust
// {{{ My Rust consts
const IMPORTANT_NUMBER: i32 = 1;
// }}}
```

## Desktop

- OS: Windows
- Terminal: Neovide GUI and Powershell

## Neovim Version

```
:version
NVIM v0.9.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe /MD /Zi /O2 /Ob1  -W3 -wd4311 -wd4146 -DUNIT_TESTING -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_WIN32_WINNT=0x0602 -DMSWIN -DINCLUDE_GENERATED_DECLARATIONS -ID:/a/neovim/neovim/.deps/usr/include/luajit-2.1 -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include -ID:/a/neovim/neovim/build/cmake.config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"
```

**Comment by feoh** [comment] 2023-08-19 20:40
Hi.

Please file this bug against the LSP you're using unless you explicitly know that the problem is with the configuration that kickstart.nvim provides.

Thanks for the report but I'm closing this for now.

**Closed by feoh** 2023-08-19 20:40 UTC
