### ISSUE TITLE
FileType Autocommands: attempt to call field 'start' (a nil value)

### ISSUE THREAD

**Issue by MarcinOrlowski** [nvim-lua/kickstart.nvim#128] opened 2023-01-11 19:30 UTC
I freshly installed neovim and followed [this](https://www.youtube.com/watch?v=stqUbv-5u2s) tutorial. Once I created local `init.lua` with the content from this repo, restarted the nvim and completed the installation. Now,  I am facing this error while opening `init.lua` file again:

```
Error detected while processing FileType Autocommands for "*":
Error executing lua callback: .../start/nvim-treesitter/lua/nvim-treesitter/highlight.lua:19: attempt to call field 'start' (a nil value)
stack traceback:
.../start/nvim-treesitter/lua/nvim-treesitter/highlight.lua:19: in function 'attach'
...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:505: in function 'attach_module'
...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:528: in function 'reattach_module'
...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:131: in function <...er/start/nvim-treesitter/lua/nvim-treesitte
r/configs.lua:130>
```

**Environment**

- Using Kubuntu 22.10
- NVIM v0.7.2
- Build type: Release
- LuaJIT 2.1.0-beta3

**Comment by MarcinOrlowski** [comment] 2023-01-11 19:39
Update: when I uninstalled official neovim package and installed from release `*.deb`, the issues seem to be gone, yet that's v0.8.2 while older version is causing a problem. Maybe it needs check for nvim version?

**Comment by jherven** [comment] 2023-01-18 08:04
Encountered the same problem with v0.7.2 (Which is the latest stable version you get by using the PPA for Ubuntu linked on their installation page). As this config states it will only support latest stable & nightly I guess it's totally fine, but very easy to miss when you assume you're on the latest version. Not until I saw this post I realized v7 is not.

**Comment by cprn** [comment] 2023-01-21 06:19
@jherven  from [README.md](https://github.com/nvim-lua/kickstart.nvim/blob/master/README.md):

> Kickstart.nvim targets only the latest ['stable'](https://github.com/neovim/neovim/releases/tag/stable) and latest ['nightly'](https://github.com/neovim/neovim/releases/tag/nightly) of Neovim. If you are experiencing issues, please make sure you have the latest versions.

For now the easiest way to update NeoVim on ubuntu is to go for unstable version - this will install `0.9.0-dev` which right now works perfectly fine for me in production environment:
```
sudo add-apt-repository ppa:neovim-ppa/unstable
sudo apt update
```

**Comment by jherven** [comment] 2023-01-21 10:40
> @jherven from [README.md](https://github.com/nvim-lua/kickstart.nvim/blob/master/README.md):
> 
> > Kickstart.nvim targets only the latest ['stable'](https://github.com/neovim/neovim/releases/tag/stable) and latest ['nightly'](https://github.com/neovim/neovim/releases/tag/nightly) of Neovim. If you are experiencing issues, please make sure you have the latest versions.

Sorry if I explained myself badly. Yes that's exaclty what I meant I used 0.7 which as you say is not supported by the config so was my own fault. 

> For now the easiest way to update NeoVim on ubuntu is to go for unstable version - this will install `0.9.0-dev` which right now works perfectly fine for me in production environment:
> 
> ```
> sudo add-apt-repository ppa:neovim-ppa/unstable
> sudo apt update
> ```
Tried the nightly first but got some other problems with some LSP. Went for the snap package instead installed stable 0.8 and all was fine after that.

**Comment by cprn** [comment] 2023-01-21 11:04
IDK what to tell you. It's by design. If you've figured it out then what else can be done in this issue? Probably could be closed by the author.

@MarcinOrlowski 
> Maybe it needs check for nvim version?

I don't think there's much sense. Stable PPA doesn't include v0.8.2 because the tag wasn't signed by Justin. I think official repo didn't update yet because of the same reason (they might mend it somehow in the next few weeks, who knows). For that exact reason [Neovim install instructions](https://github.com/neovim/neovim/wiki/Installing-Neovim#ubuntu) mention both stable and unstable PPA. The check you're talking about could be made downstream in `nvim-treesitter` or better yet upstream in `nvim` itself.

**Comment by jherven** [comment] 2023-01-21 11:27
> IDK what to tell you. It's by design. If you've figured it out then what else can be done in this issue? Probably could be closed by the author.
> 
I neither have any issues nor complains. Finding this issue helped me notice my mistake so I just wanted to add that some info to other people that did the same.

**Comment by B1Z0N** [comment] 2023-02-05 17:02
This is just the same as mine. It seems that I've created duplicate issue #163

**Comment by tjdevries** [comment] 2023-02-15 21:33
Looks like the version was too old -- I'll close this. Thanks everyone

**Closed by tjdevries** 2023-02-15 21:33 UTC
