### ISSUE TITLE
How search match count display? which config or plugin did this?

### ISSUE THREAD

**Issue by autokxs** [nvim-lua/kickstart.nvim#1246] opened 2024-11-29 15:30 UTC
who can help me understand which config or plugin enable the search match count display?
in my own, it only shows in the status line instead of just display right of the matched words like kickstart.

**Comment by feoh** [comment] 2024-12-12 16:07
I took a spin through the code and couldn't find this.

Might it be a Telescope configuration setting?

@tjdevries Sorry to bother you good sir but do you have any thoughts on this one?

**Comment by feoh** [comment] 2024-12-29 17:24
Hi.

I tried to repro this and can't.  Here's a screenshot with no LSPs enabled, but I saw identical behavior in a Python buffer.

I'd recommend commenting out bits of your init.lua to understand which plugin is causing this behavior if you're seeing something unusual on your end.

I've attached a screenshot of what I'm seeing, and I think this is the behavior we want.

<img width="1280" alt="Screenshot 2024-12-29 at 12 21 55 PM" src="https://github.com/user-attachments/assets/20a4c40e-b971-4838-af2f-60b725a09d67" />

Closing because as near as I can tell we're working as designed.

**Closed as completed by feoh** 2024-12-29 17:24 UTC
