### ISSUE TITLE
Checkout of some plugins failing

### ISSUE THREAD

**Issue by Paiusco** [nvim-lua/kickstart.nvim#807] opened 2024-03-29 13:50 UTC
## Describe the bug
I'm not being able to finish the kickstart installation due to failures of **some plugins** checkouts (looks like not related directly to kickstart itself, but I've only seen it here).

Also found that [this may happen if proxies are configured for http(s)](https://stackoverflow.com/questions/20370294/git-could-not-resolve-host-github-com-error-while-cloning-remote-repository-in), which is not the case, as if I try manually to clone any of those repos, it just works fine. I anyway run those commands (even with a blank `.gitconfig`) and no change.
![image](https://github.com/nvim-lua/kickstart.nvim/assets/2374887/f9b4d0ae-4ecb-4c5f-add7-0de378bc8744)

I start with 13 failed, if I keep trying to S (Sync), I can go down a bit, but never a full installation. 

## To Reproduce
1. Delete `~/.config/nvim`
2. Delete `~/.local/share/nvim/`
3. Clone this repo into `~/.config/nvim`
4. I've even clean-up my `.gitconfig` and restarted to make sure git was not weirdly configured.
6. Start nvim
7. Get errors for some of the plugins saying it can clone but not checkout

## Desktop
- OS: Arch Linux 6.8.2-arch2-1
- Terminal: alacritty

## Neovim Version
```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

```

**Comment by feoh** [comment] 2024-03-29 14:42
Hi!

It looks to me like the problem is that lazy.nvim doesn't support connecting to github via proxies.

Please file an issue against [their repository](https://github.com/folke/lazy.nvim) citing these details including your proxied use case.

Thanks for the report but I'm closing this for now as it's not specifically a kickstart.nvim problem.

**Closed by feoh** 2024-03-29 14:42 UTC

**Comment by folke** [comment] 2024-03-29 21:55
As mentioned multiple times before, this is **not** a lazy.nvim issue.
This is a problem with your computer/network/ISP/proxy or whatever is in between your terminal and github.com.
