### ISSUE TITLE
After folder does not override past end of lazy block

### ISSUE THREAD

**Issue by jbwyatt4** [nvim-lua/kickstart.nvim#205] opened 2023-03-01 05:56 UTC
**Describe the bug**
Trying to override settings after lazy block like mouse mode does not work as it is called before the default init file sets it.

The idea is just to keep all my custom config in after/plugin or lua/custom folders. On line 181 the init file notes that these folders can be used to keep any custom config and that does not seem to be true for certain items. I can easily remove the line I just want to know if there was a way I was missing.

**To Reproduce**
1. Place .lua file in after/plugin/somefile.lua with vim.opt.mouse = ''
2. Right click on some text from a file. Mouse mode will not be overridden.

**Desktop (please complete the following information):**
- OS: Fedora 37 Gnome
- Terminal: Gnome terminal

** Neovim Version **
 - Output of running `:version` from inside of neovim:

```
:version                                                                                                 
NVIM v0.8.3
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wa
ll -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/re
dhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=gener
ic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -DNVIM_TS_HAS_SET_MATCH_LIMIT -DN
VIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -
std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing
-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DI
NCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG
_LEVEL=3 -I/builddir/build/BUILD/neovim-0.8.3/redhat-linux-build/cmake.config -I/builddir/build/BUILD/neov
im-0.8.3/src -I/usr/include -I/usr/include/luajit-2.1 -I/builddir/build/BUILD/neovim-0.8.3/redhat-linux-bu
ild/src/nvim/auto -I/builddir/build/BUILD/neovim-0.8.3/redhat-linux-build/include
Compiled by mockbuild@koji

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

```

**Comment by feoh** [comment] 2023-05-15 16:40
Resolving as duplicate of #300

**Closed by feoh** 2023-05-15 16:40 UTC
