### ISSUE TITLE
Blue-ish theme after install

### ISSUE THREAD

**Issue by fabianschwarzfritz** [nvim-lua/kickstart.nvim#81] opened 2022-12-21 15:23 UTC
**Describe the bug**
After install successfully installing `nvim` from scratch, I added this lua config file and ran `PackerInstall` via `nvim`. The installation seems to succeed but the color scheme looks super off. I have made no changed from the init.lua (version from commit 521940693e10eee57f4e67dce960d2229c1441d3 ) .

The background is blue and this does not look like the `onedark` theme. 🙂 

This is a fresh installation on nvim on a mac machine (`sw_vers -productVersion` gives macos `13.0.1`.

I know this is very little information, so if you need anything or have any idea of useful information that I could provide to find the issue / bug I am happy to do so. 

Have a look at the screenshot: 

![Bildschirm­foto 2022-12-21 um 16 18 17](https://user-images.githubusercontent.com/1759672/208939611-ff9e9b21-7cb4-4a72-b298-7ff9a56392fa.png)

**To Reproduce**
1. Run on mac `13.0.1` with the default Terminal app.
1. Fresh install of `nvim`
2. Create `init.lua` 
3. Run `PackerInstall`
4. Close and re-open neovim

**Desktop (please complete the following information):**
- OS: MacOS `13.0.1`
- Terminal: Default macos terminal

** Neovim Version **
 - Output of running `:version` from inside of neovim:

```
:version
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.8.1/share/nvim"

Run :checkhealth for more info
```

Other than that: Cool tool, I always searched for a nice way installing quickly a vim version with good defaults that go beyond the default editor :) !! Nice work!

**Comment by craigmac** [comment] 2022-12-21 15:30
Duplicate of https://github.com/nvim-lua/kickstart.nvim/issues/68

**Comment by mutairibassam** [comment] 2022-12-21 17:25
@fabianschwarzfritz I had the same issue and solved it by commenting `color` properties.

```lua
-- Set colorscheme
--vim.o.termguicolors = true                       -> (will remove the green highlight)
--vim.cmd [[colorscheme onedark]]                  -> (will remove the blue background)
```

**Comment by tjdevries** [comment] 2022-12-21 18:26
Duplicate of #68

**Closed by tjdevries** 2022-12-21 18:26 UTC

**Comment by fabianschwarzfritz** [comment] 2022-12-21 21:38
Thanks for the updates and hints and sorry for the duplicate!

**Comment by tjdevries** [comment] 2022-12-24 06:37
No prob :)
