### ISSUE TITLE
nvim-treesitter Shows error when launching nvim for the first time.

### ISSUE THREAD

**Issue by V3dantSh4rma** [nvim-lua/kickstart.nvim#322] opened 2023-05-25 12:43 UTC
# Error
```
Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: C:/Program Files/Neovim/share/nvim/runtime/filetype.lua:22: Error executing lua: C:/Program Files/Neovim/share/nvim/runtime/filetype.lua:23: Vim(append):Error executing lua callback: Failed to load parser: uv_dlopen: C:\Users\stanp\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\lua.so is not a valid Win32 application.
```

# Description
For those who will gonna say that I have to go through [Nvim-treesitter official Windows Support](https://github.com/nvim-treesitter/nvim-treesitter/wiki/Windows-support#troubleshooting). I did that. I also went through troubleshooting. Now, The thing is that I have 0 knowledge of Lua and no fucking knowledge on how to use it.

![image](https://github.com/nvim-lua/kickstart.nvim/assets/70263758/a4cc3a49-41f4-49cf-b64e-d7f475cbbb94)

I was able to get past step 1, but not past of second step which is adding that line. I know that my init.lua file is in the nvim directory on windows.

My directory structure is as follows;
```
├── nvim
│   └── init.lua
└── nvim-data
    └── lazy
        └── nvim-treesitter
            └── lua
                └── nvim-treesitter
                    └── install.lua
```

Line I want to add and which is also not working: 
```require 'nvim-treesitter.install'.compilers = { "clang" }```

The above one shows an import error or ``Unable to load the lua file``. Please help me as I am really stuck here even after ChatGPT'ing.

**Comment by feoh** [comment] 2023-05-25 13:47
This is a duplicate of #236. Closing.

**Closed by feoh** 2023-05-25 13:47 UTC
