### ISSUE TITLE
C++ header files not found

### ISSUE THREAD

**Issue by dipyamanroy** [nvim-lua/kickstart.nvim#193] opened 2023-02-22 02:00 UTC
**Describe the bug**
C++ header files such as `<iostream>` not found.

**To Reproduce**
1. Install `clangd` on an Ubuntu (or derivative) distribution. (Using `apt install clangd`)
2. Uncomment `clangd = {}` in the `init.lua`.
3. Edit a `.cpp` file and add some header files. 
4. Error shown as follows:
![image](https://user-images.githubusercontent.com/92980894/220501156-a1d08261-b078-40cd-a615-bf131e11d075.png)

**Desktop (please complete the following information):**
- OS: Pop!_OS
- Terminal: gnome-terminal

**Neovim Version**
 - Output of running `:version` from inside of neovim: 

```
NVIM v0.9.0-dev-635+gc19bd47c0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by dipper@pop-os
```

**Comment by nicolas-mateo** [comment] 2023-02-26 16:08
Any luck so far?

**Comment by Alexis12119** [comment] 2023-03-03 14:11
I think you need `compile_commands.json` to fix that error.

**Comment by Alexis12119** [comment] 2023-03-03 22:28
I think you need `compile_commands.json` to fix that error.

**Comment by vzsky** [comment] 2023-03-29 04:24
Any ways to not having `compile_commands.json` but rather pass the include path to clangd argument from the .lua setup file?

**Comment by Corgile** [comment] 2023-03-31 02:58
Same issue here, any suggestions?

### Problem

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/48396880/229011516-54ea4401-382d-4a7f-93dd-ef72ec46761e.png">

### LSP info

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/48396880/229011611-3a87b600-8d39-4334-b1ec-1c681579f605.png">

**Comment by feoh** [comment] 2023-05-15 16:37
Duplicate of #238

**Closed by feoh** 2023-05-15 16:37 UTC
