### ISSUE TITLE
treesitter error on every vim.cmd 

### ISSUE THREAD

**Issue by mmngreco** [nvim-lua/kickstart.nvim#37] opened 2022-11-30 19:55 UTC
Hi guys,

I was checking this promising config when I found this issue:

![image](https://user-images.githubusercontent.com/6231413/204895231-5a3084f2-ae87-45be-aaf6-293ea6407299.png)

This happen on every `vim.cmd` line 

![image](https://user-images.githubusercontent.com/6231413/204895338-fbcff2c0-fbc3-4696-a2c8-33dfade44ab2.png)

I made sure that I have treesitter syntax updated with `TSUpdate`.

**Comment by mmngreco** [comment] 2022-11-30 20:00
I've fixed those changing by `vim.cmd.packadd "packer.nvim"` and `vim.cmd.colorscheme "onedark"` , this is correct? you want a PR?

**Comment by tjdevries** [comment] 2022-12-02 03:40
Hm, this happened with the latest nvim & plugins? Yeah, if you can send a PR that'd be helpful (i couldn't reproduce earlier)

**Comment by mmngreco** [comment] 2022-12-03 17:46
weird, I can't reproduce it anymore :-/

**Comment by tjdevries** [comment] 2022-12-07 02:11
I think this is fixed with #39

**Closed by tjdevries** 2022-12-07 02:11 UTC
