### ISSUE TITLE
debugpy fails to run on second launch with mason-nvim-dap

### ISSUE THREAD

**Issue by bcatubig** [nvim-lua/kickstart.nvim#500] opened 2023-11-10 17:16 UTC
## Describe the bug
Python debugging with nvim-dap-python works once and then fails afterwards.

After a fresh nvim install, I am able to debug a python file with DAP without issue. After closing nvim and re-attempting to debug a python file with dap, an exception is raised.

## To Reproduce

```shell
clear nvim share
rm -rf ~/.local/share/nvim

# launch nvim / installing packages
nvim some_thing.py
```
- Set a breakpoint
- Run `:DapContinue`
- Exit Nvim
- Open a python file
- Set a breakpoint
- Run `:DapContinue` 

### Error
```
...ndon/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1418: adapter.command must not b
e empty. Got: {
  command = "",
  type = "executable"
}
stack traceback:
^I[C]: in function 'error'
^I...ndon/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1418: in function 'spawn'
^I/home/brandon/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:1038: in function 'launch'
^I/home/brandon/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:373: in function 'run_adapter'
^I/home/brandon/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:408: in function 'maybe_enrich_c
onfig_and_run'
^I/home/brandon/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:504: in function </home/brandon/
.local/share/nvim/lazy/nvim-dap/lua/dap.lua:488>
^I[C]: in function 'xpcall'
^I/home/brandon/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:531: in function </home/brandon/
.local/share/nvim/lazy/nvim-dap/lua/dap.lua:530>
Press ENTER or type command to continue
```

Output of `:lua print(vim.fn.exepath('debugpy-adapter'))`

```
/home/brandon/.local/share/nvim/mason/bin/debugpy-adapter
```
ref: https://github.com/jay-babu/mason-nvim-dap.nvim/blob/main/lua/mason-nvim-dap/mappings/adapters/python.lua

**My Config**
ref: https://github.com/bcatubig/kickstart.nvim/blob/master/lua/kickstart/plugins/debug.lua

## Desktop

- OS: OSX/Linux
- Terminal: iterm2/Konsole

## Neovim Version

```
:version                                                                          
NVIM v0.9.4
Build type: RelWithDebInfo
LuaJIT 2.1.1692716794
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstric
t-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -W
missing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fall
through -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERAT
ED_DECLARATIONS -D_GNU_SOURCE -I/home/brandon/code/neovim/.deps/usr/include/luajit-2.1 -I/us
r/include -I/home/brandon/code/neovim/.deps/usr/include -I/home/brandon/code/neovim/build/sr
c/nvim/auto -I/home/brandon/code/neovim/build/include -I/home/brandon/code/neovim/build/cmak
e.config -I/home/brandon/code/neovim/src -I/usr/include -I/home/brandon/code/neovim/.deps/us
r/include -I/home/brandon/code/neovim/.deps/usr/include -I/home/brandon/code/neovim/.deps/us
r/include -I/home/brandon/code/neovim/.deps/usr/include -I/home/brandon/code/neovim/.deps/us
r/include -I/home/brandon/code/neovim/.deps/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Comment by feoh** [comment] 2023-11-10 17:51
Hi. Please file this issue against the neovim-dap-python plugin repository, or perhaps Mason?

In any case, this is not a bug with kickstart.nvim and I am closing it for now. Thank you for your contribution.

**Closed by feoh** 2023-11-10 17:51 UTC
