### ISSUE TITLE
treesitter error when opening nvim

### ISSUE THREAD

**Issue by Yakiyo** [nvim-lua/kickstart.nvim#411] opened 2023-08-28 09:36 UTC
I just cloned kickstart and wanted to start using it, after all plugins were downloaded, i closed and reopened neovim. And i get the following error.

![image](https://github.com/nvim-lua/kickstart.nvim/assets/91675932/880c6978-639d-45d8-aed6-e5fd9e9c3d80)

I'm on windows, using neovim v0.9.1, and am using it through Git Bash

**Comment by feoh** [comment] 2023-08-29 10:57
Hi.

This is a known issue with Neovim on Windows and isn't connected with kickstart.nvim

The problem is that treesitter expects you to have your C compiler on the PATH before it starts, otherwise you get this error.

I recommend always running Neovim from the "Visual Studio Command Prompt" as apparently adding the C compiler to your path is Bad Juju on Windows? :shrug: I actually rather enjoy aspects of modern Windows but this is a giant wart on the face of the Neovim experience there. Sorry.

Closing for now as this is an upstream problem.

**Closed by feoh** 2023-08-29 10:57 UTC
